### PR TITLE
Deprecate old extension + v1.17.0

### PR DESCRIPTION
**Pull request by jafeltra**
**Description:** This PR deprecates the old MITRE-Health version of the extension.

This PR will go into a branch, which we can then publish to the old publisher. I followed the same process as the last time we switched publishers, so this PR is similar to #30.

**Testing Instructions:** There shouldn't be any functionality left, so check that all the relevant files have been removed. There isn't a way to test that the `extensionDependencies` works as expected until we publish to the marketplace.

**Next Steps:** Once this is merged to a branch and we've published the new extension to the new publisher, I can publish this branch to the MITRE-Health publisher. It looks like I can also have VS Code mark this extension as deprecated, so I'll plan to do that as well.

However, if anyone thinks it would be better to just mark the extension as deprecated, I can close this PR and leave the MITRE-Health extension as is and have VS Code mark it as deprecated. That doesn't seem to be an immediate process, so it might be nice to do our own thing, but I'm open to your opinion.

### CODE REVIEW

**Comment by jafeltra** [comment]
Based on our discussion, I tried making it so the old version of the extension installs the new version of the extension and installs itself.

However, I did have a hard time testing whether this works as expected. You should be able to build the extension yourself by running `vsce package`. That will create a .vsix file. Then in VS Code, on the Extensions pane, using the three dots menu, you should be able to click "Install from VSIX..." and choose the .vsix file you just created. However, when I do this, I see the deprecated extension readme and I see no functionality when I try to use it, but it doesn't uninstall itself. Obviously there is no new version of the extension yet, but I tried to install a different extension, and I couldn't see that working either.

So, not a straightforward win. I haven't found any documentation saying that it _won't_ work locally, so this does make me a little suspicious. I kept that work in a separate commit ([1814a34](https://github.com/standardhealth/vscode-language-fsh/pull/91/commits/1814a341e4f3f1ee0ee5827da5b62e4cd9b988f2)), so I can revert that commit if we change our mind on this functionality.

**Comment by jafeltra** [comment]
As mentioned earlier and discussed outside of GitHub, I reverted the commit that tries to uninstall the extension. So now this branch does the following:

- removes all functionality from the extension
- indicates that the extension is deprecated
- uses the `extensionDependencies` array to auto-install the new extension
- points the user to the new extension and tells them they can uninstall once they have that new version

**Comment by jafeltra** [comment]
Now that the new extension is published, I tested this extension and confirmed the new extension is installed when you install this one. I think this is set to be reviewed.

Once approved, it'll be merged into `deprecated-2024`, and I'll publish that branch to the old extension.

**Review by cmoesel — APPROVED** [review]
I tested this locally and it worked exactly as advertised! But dang... GitHub really wants you to resolve some conflicts.

**Review by mint-thompson — APPROVED** [review]
Confirmed that when I installed this extension, it automatically installed the new `FHIR-Shorthand.vscode-fsh` extension.

**Pull request merged**
