### PR TITLE
Update syntax highlighting

### PR DESCRIPTION
**Pull request by cmoesel**
Update language configuration:
* reformat for readability
* add block comments to comments and autoClosingPairs

Update syntax:
* highlight numbers
* highlight ucum code in quantities
* highlight Reference() and Canonical()
* don't highlight system when used as path

Before updates:
image

After updates:
image

### CODE REVIEW

**Comment by cmoesel** [comment]
Oh, and a bonus `npm audit --fix` because GitHub complained about a vulnerability.

**Review by mint-thompson — CHANGES_REQUESTED** [review]
I noticed something a little bit off with the way invariant names are highlighted. Because invariant names are often of the form `abc-1`, the `-1` part gets highlighted as a number. I've attached a screenshot showing this.
image

**Comment by cmoesel** [comment]
> I noticed something a little bit off with the way invariant names are highlighted. Because invariant names are often of the form `abc-1`, the `-1` part gets highlighted as a number. I've attached a screenshot showing this.

Dang... Good find.

**Review by jafeltra — COMMENTED** [review]
I reviewed and haven't noticed anything else besides what @mint-thompson pointed out!

**Comment by cmoesel** [comment]
OK, 018eb03 fixes the issue that @mint-thompson found.  It also fixes an issue where some keywords would not highlight if they started on column 0 (like if the author wrapped the rule over multiple lines).

**Review by jafeltra — APPROVED** [review]
Looks good to me!

**Review by mint-thompson — APPROVED** [review]
looks good to me!

**Pull request merged**
