### PR TITLE
Add documentation link to context menu

### PR DESCRIPTION
**Pull request by mint-thompson**
Completes task [CIMPL-341](https://standardhealthrecord.atlassian.net/browse/CIMPL-341).

When the user right-clicks in a FSH file, a new menu option "Open FHIR Documentation" is shown. When the user selects this option, the extension checks to see if it can find a documentation page for the selected word. FSH entity names have specific pre-defined pages to open, but in other cases, the normal FHIR documentation is checked. The check itself is a simple HEAD request. If it succeeds, the page opens in the browser (possibly with a preceding confirmation prompt, based on the user's settings). If it fails, an informational message is shown instead.

I am reasonably confident in the way that the extension is functioning. The primary thing I'd like to get opinions about is the specific pages I defined for FSH documentation. I went with FHIR docs for Profile and Extension, and with FSH-specific docs for other FSH entities.

### CODE REVIEW

**Review by cmoesel — COMMENTED** [review]
This is very cool and I love that we can write tests for this stuff!  This is all technically correct and I'd feel comfortable merging it.  That said, I have a few comments and questions for your consideration:

1. Regarding where `profile` and `extension` should go... I'm a little torn.  On one hand, the HL7 pages you link to are very helpful.  On the other hand, it seems inconsistent since other keywords link to FSH documentation.  I think the ideal solution would be to link to the FSH documentation _and for the FSH documentation to clearly link to these very helpful FHIR pages_ (which it currently does not do, but we could make that change).
2. Since we link some keywords to FSH doc, we might consider extending support to all of the meaningful keywords (e.g., `only` links to doc on Only rules, `obeys` links to doc on Obeys rules, etc).
3. If I right-click a URL, it currently selects only the immediate part of the URL I right-clicked (rather than full URL).  Ideally it would detect the full URL and check to see if it can be opened directly.
4. If the above works (navigating to URLs), then the next step would be to make the extension alias-aware so if I right-click an alias and say to open the FHIR definition, it acts the same as if I had right-clicked the URL.  (This can definitely be a separate task for the future).
5. We might want to consider being FHIR version aware.  E.g., if there is a `sushi-config.yaml` file that indicates an R5 version of FHIR, maybe we shouldn't be opening the R4 definitions? (This can also be a task for the future since this is a slim minority use case right now).
6. I also noticed that error messages (when there is no corresponding page) are sticky.  You need to explicitly close them.  Is there a way to make it work more like when you attempt `rename symbol` on something that is not a symbol? (screenshot below)
  image


These aren't _must-haves_, but I'd be interested in your thoughts about them.

**Review by jafeltra — COMMENTED** [review]
This looks really good! I think I agree with Chris that I'm torn between linking to the FSH documentation and the FHIR documentation. I like Chris's idea to link to the FHIR pages within the FSH page, and I think that would be my ideal, but if we link to the `hl7.org/fhir` version of the documentation, will it take a new release to see those changes? How frequently is that page updated?

One thing I noticed is that right clicking on the word `extension` within a path will also open the documentation link for Extensibility. Is this something we expect to happen or don't mind? It seemed a little unexpected to me, but I think it is technically correct since that path is referring to an extension. However, if we switch to viewing the FSH documentation, it might not be technically correct anymore.

**Comment by jafeltra** [comment]
Oh I also meant to ask this yesterday too, but do you think we should include a screenshot for the Open FHIR Documentation section of the README? There's probably not much to put into a GIF but I don't want it to be overshadowed by the cool GIFs!

**Review by cmoesel — APPROVED** [review]
Awesome.  This extension just keeps getting better and better.

I added a GIF for the new feature.  @mint-thompson and/or @jafeltra -- please review it and let me know if there are any issues.  If not, this has my approval.

**Review by jafeltra — APPROVED** [review]
This looks good to me! And the GIF looks nice!

**Pull request merged**
