### PR TITLE
Updates grammar files to the 2.0.0 beta 1 grammar

### PR DESCRIPTION
**Pull request by julianxcarter**
Updates the grammar files to be in line with sushi 2.0.0-beta 1.

### CODE REVIEW

**Review by ngfreiter — DISMISSED** [review]

**Comment by cmoesel** [comment]
Does "Go to Definition" work for going to Logical Model or Resource definitions?  Or is there additional code needed to do that?

**Comment by mint-thompson** [comment]
> Does "Go to Definition" work for going to Logical Model or Resource definitions? Or is there additional code needed to do that?

I think new code will be needed, since the definition provider has to check for [specific entity types](https://github.com/standardhealth/vscode-language-fsh/blob/master/src/FshDefinitionProvider.ts#L208).

**Comment by cmoesel** [comment]
@julianxcarter -- if you still have time on your hands, it would be wicked cool if we could get "Go to Definition" working so it can go to Logical and Resource definitions...  Let me know what you think!

**Comment by julianxcarter** [comment]
> @julianxcarter -- if you still have time on your hands, it would be wicked cool if we could get "Go to Definition" working so it can go to Logical and Resource definitions... Let me know what you think!

Done!

**Comment by jafeltra** [comment]
Can you potentially add a very small addition to the syntax highlighting to include the `+` so it highlights in soft indexing? You should be able to just add `\\+` to the list of `keyword.tokens.fsh`, so that line 58 looks like:

```
"match": "\\*|->|=|\\+|:"
```

**Comment by jafeltra** [comment]
I tried out the Go to Definition for Logical and Resource and it worked great! I'm not sure if it's feasible now and I'm not 100% if it's needed, but it seems like it would be nice to have a unit test check that we can Go To Definitions of Logical Models and Resources. @mint-thompson probably has a much better idea of if that is a helpful test than I do.

**Review by jafeltra — APPROVED** [review]
This looks awesome! Thanks for making those updates!

**Comment by julianxcarter** [comment]
@jafeltra Nice catch! I've added in highlighting for `+`s, and also added in some simple tests that just ensure that Logical Models and Resources are properly scanned by the extension.

**Comment by julianxcarter** [comment]
@jafeltra Absolutely! Thanks for catching them 🙂

**Review by ngfreiter — APPROVED** [review]

**Pull request merged**
